---
development:
  cloud_name: hssucrsej
  api_key: '889382371289373'
  api_secret: eLAoR1wv5R9h6onnC_g8HPDUuek
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hssucrsej
  api_key: '889382371289373'
  api_secret: eLAoR1wv5R9h6onnC_g8HPDUuek
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hssucrsej
  api_key: '889382371289373'
  api_secret: eLAoR1wv5R9h6onnC_g8HPDUuek
  enhance_image_tag: true
  static_image_support: false
